Terraform config files
alliage-io/tdp-lxd pull request #1
Opened 2022-09-29 22:07 UTC by Nuttymoon

#### Which issue(s) this PR fixes:

Fixes #2 

#### Additional comments:

This PR adds the initial Terraform config files to the repo. All containers configuration are located in `local.auto.tfvars`.

#### Acknowledgment

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [SAS Adaltas](https://www.adaltas.com/), you have to acknowledge this by using the following check-box.

- [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

- [x] I hereby agree to grant [Adaltas](https://www.adaltas.io/) a copyright license to use my contributions.

2022-09-30 07:07 UTC, gboutry commented on README.md
> +
Ansible is missing in requirements

2022-09-30 07:14 UTC, wdavidw requested changes

2022-09-30 07:14 UTC, wdavidw commented on LICENSE
> +
License is MIT, Copyright is Adaltas

2022-09-30 08:39 UTC, leopaul36 commented on local.auto.tfvars
> +tdp_image = "images:centos/7"
Should we move to a more modern image / distro?

LXD fails on my side with `The image used by this instance requires a CGroupV1 host system` in Fedora 36

Romain has been working to make `tdp-collection-prerequisites` work with Rocky 8 so maybe we should use `images:rockylinux/8`?

2022-09-30 08:47 UTC, wdavidw commented on local.auto.tfvars
> +tdp_image = "images:centos/7"
Yes we should. For OECD, I don't wish to deploy with such a legacy OS as centos 7, we should validate Rocky as early as possible.

2022-09-30 10:45 UTC, Nuttymoon commented on LICENSE
> +
Don't we wanna use the same license as all TDP projects (Apache 2.0)?

2022-09-30 12:15 UTC, wdavidw commented on LICENSE
> +
Note, MIT is fine and compatible

2022-09-30 17:24 UTC, Nuttymoon commented on local.auto.tfvars
> +tdp_image = "images:centos/7"
Working on this.

2022-10-03 08:46 UTC, Nuttymoon commented
Changed license and moved to Rocky 8 image by default. Updated README accordingly.

2022-10-03 12:27 UTC, merged